### ISSUE TITLE
error running the full process

### ISSUE THREAD

**Issue by jeanpommier** [OMP-IRD/hyfaa-scheduler#1]
To run the full process, with the decommented lines https://github.com/OMP-IRD/hyfaa-scheduler/blob/master/work_configurations/operational_niger_gsmap/run.sh#L17-L41, I'm getting some errors in the process:
```
scheduler_1_ea38e414d5f8 | Computing hydrological state 20210321T000000U000000 -> 20210322T000000U000000 (step 9/9):
scheduler_1_ea38e414d5f8 |   0) Writing MGB parameter files and dynamic forcing files
scheduler_1_ea38e414d5f8 |     => 2.347 seconds
scheduler_1_ea38e414d5f8 |   1) Analysis step
scheduler_1_ea38e414d5f8 |     => No data assimilated: 0.003 seconds
scheduler_1_ea38e414d5f8 |   2) Preparing 20 MGB simulations...
scheduler_1_ea38e414d5f8 |     => MGB simulations prepared successfuly: 0.310 seconds
scheduler_1_ea38e414d5f8 |   3) Launching 20 MGB simulations...
scheduler_1_ea38e414d5f8 |     => MGB simulations ended successfuly: 3.611 seconds
scheduler_1_ea38e414d5f8 |   4) Adding last_rain_data_loaded vector to MGB simulation outputs and adding resulting hydrological state to database...
scheduler_1_ea38e414d5f8 |     => 1.291 seconds
scheduler_1_ea38e414d5f8 |   => step complete : 7.56 seconds (88.88 from beginning at 2021-03-23T08:16:31)
scheduler_1_ea38e414d5f8 | Launching HYFAA post-processing...
scheduler_1_ea38e414d5f8 | Traceback (most recent call last):
scheduler_1_ea38e414d5f8 |   File "/opt/conda/lib/python3.7/site-packages/netCDF4/utils.py", line 228, in _StartCountStride
scheduler_1_ea38e414d5f8 |     e = int(e)
scheduler_1_ea38e414d5f8 | ValueError: invalid literal for int() with base 10: 'd'
scheduler_1_ea38e414d5f8 | 
scheduler_1_ea38e414d5f8 | During handling of the above exception, another exception occurred:
scheduler_1_ea38e414d5f8 | 
scheduler_1_ea38e414d5f8 | Traceback (most recent call last):
scheduler_1_ea38e414d5f8 |   File "/hyfaa/bin/hyfaa_postprocessing.py", line 320, in <module>
scheduler_1_ea38e414d5f8 |     hyfaa_postprocessing(args.input_yaml_file, verbose=args.verbose)
scheduler_1_ea38e414d5f8 |   File "/hyfaa/bin/hyfaa_postprocessing.py", line 257, in hyfaa_postprocessing
scheduler_1_ea38e414d5f8 |     data_loc = ds_science_old.variables[var_name]['data'][it0,:,:]
scheduler_1_ea38e414d5f8 |   File "netCDF4/_netCDF4.pyx", line 4384, in netCDF4._netCDF4.Variable.__getitem__
scheduler_1_ea38e414d5f8 |   File "/opt/conda/lib/python3.7/site-packages/netCDF4/utils.py", line 230, in _StartCountStride
scheduler_1_ea38e414d5f8 |     raise IndexError(IndexErrorMsg)
scheduler_1_ea38e414d5f8 | IndexError: only integers, slices (`:`), ellipsis (`...`), and 1-d integer or boolean arrays are valid indices
```
Most probably, it's related to old data interfering with updated processes. @remijugier what should I remove, from the old data, to get it running properly ?

It seems I at least fail to generate the previ datasets

**Context:**
Launching the run using the docker image. 
No change in the default configs. 
I had already launched the run using code from #ddfda5f7 (March, 8)

**Comment by remijugier** [comment]
salut Jean, effectivement il y avait une erreur que j'ai corrigée sur master. J'ai essayé de créer une branche pour l'issue mais il me le refuse. On dirait qu'on ne peut pas créer de branche, c'est bizarre, tu fais comment toi ? Perso je fait `git checkout -b nom_branche` puis `git push -u origin nom_branche`, après je fais mes modifs, je pousse dans la branche, puis je la merge, puis je la supprime sur le remote et en local.

**Comment by jeanpommier** [comment]
Peut-être que ton profil ne permet pas de créer une branche, mais ça m'étonne
Ou alors, c'est un pb de nom de remote, non ? origin, ça serait pas ton repo à magellium ?

**Comment by remijugier** [comment]
oui j'ai poussé sur master. mais en fait c'est le `git checkout -b nom_branche` qui passe pas, il me dit que la branche n'existe pas, alors que d'habitude ça la créé

**Comment by jeanpommier** [comment]
Hello,
Ca, ca se passe sur ton ordi, le checkout. Mais c'est bizarre
